# Generated by Django 4.1.13 on 2024-06-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("mobile_number", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=50)),
                ("course", models.CharField(max_length=50)),
            ],
        ),
    ]
